### ISSUE TITLE
Page: Update Services

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#18]
**wordpress/update-services.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/wordpress/update-services.md

- [x] Add into a Category 
- [x] Page creation
- [x] Copy the original content
- [x] Format the content 
- [x] Create a PR

**Comment by dsmith4-godaddy** [comment]
Takin' a look

**Comment by dsmith4-godaddy** [comment]
https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/51
