### ISSUE TITLE
Page: Updating WordPress using FTP

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#22]
**upgrade/ftp.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/upgrade/ftp.md

- [x] Add into a Category 
- [x] Page creation
- [x] Copy the original content
- [x] Format the content 
- [x] Create a PR

**Comment by dsmith4-godaddy** [comment]
Taking a look at this page

**Comment by dsmith4-godaddy** [comment]
https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/48 copies the top FTP page and the Filezilla page.
