### ISSUE TITLE
Page: phpMyAdmin

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#23]
**upgrade/phpmyadmin.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/upgrade/phpmyadmin.md

- [x] Add into a Category 
- [x] Page creation
- [ ] Copy the original content
- [ ] Format the content 
- [ ] Create a PR

**Comment by javiercasares** [comment]
Taken by Patrick Dolan

**Comment by 7PDaddy** [comment]
# phpMyAdmin

## What is phpMyAdmin?
An administrator’s tool of sorts, phpMyAdmin is a PHP script meant for giving users the ability to interact with their MySQL databases. WordPress stores all of its information in the MySQL database and interacts with the database to generate information within your WordPress site. A “raw” view of the data, tables and fields stored in the MySQL database is accessible through phpMyAdmin.

## What is it good for?
The phpMyAdmin program is handy for performing maintenance operations on tables, backing up information, and editing things directly in the event that WordPress is not working. Occasionally, in the [Support Forums](https://wordpress.org/support/welcome/#asking-for-support), someone will post a SQL query of some benefit or other that can be run using phpMyAdmin. Although many of the same tasks can be performed on the MySQL command line, doing so is not an option for many people.

## Where can I get it?
Often host control panels, such as cPanel and Plesk, have phpMyAdmin pre-installed, so there is nothing special you have to do to use it. It is usually linked from the database page. Ask your host if this is available.

You can download phpMyAdmin yourself and install it from the main [phpMyAdmin project page](https://www.phpmyadmin.net/).

**Comment by 7PDaddy** [comment]
Updated above for https://wordpress.org/support/article/phpmyadmin/
