### ISSUE TITLE
Page: Migrating WordPress

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#25]
**upgrade/migrating.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/upgrade/migrating.md

- [x] Add into a Category 
- [x] Page creation
- [x] Copy the original content
- [x] Format the content 
- [x] Create a PR

**Comment by jessfrick** [comment]
Going to start working on this one.
