### ISSUE TITLE
Page: Must Use Plugins

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#31]
**plugins/mu-plugins.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/plugins/mu-plugins.md

- [x] Add into a Category 
- [x] Page creation
- [ ] Copy the original content
- [ ] Format the content 
- [ ] Create a PR

**Comment by javiercasares** [comment]
Taken by David Smith

**Comment by dsmith4-godaddy** [comment]
https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/44 will address the initial migration.
