### ISSUE TITLE
Page: Security

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#33]
**security/security.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/security/security.md

- [x] Add into a Category 
- [x] Page creation
- [x] Copy the original content
- [x] Format the content 
- [x] Create a PR

**Comment by thomas-price** [comment]
Hi @javiercasares 
After the original content is copied over, would you like assistance to further develop the structure and content?

**Comment by javiercasares** [comment]
This is part of the phase 2 of the project. If a page can be evolved, or merge with also some other pages from the WordPress Network (there is a lot of info about Security in the Hosting and Core pages) we can add that, but we need to notify some other teams.

Right now, the project is focused on moving documentation from de UserHub and DevHub, but it's not limited to that :)
