### ISSUE TITLE
Page: Debugging in WordPress

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#36]
**debug/debug-wordpress.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/debug/debug-wordpress.md

- [x] Add into a Category 
- [x] Page creation
- [X] Copy the original content
- [x] Format the content 
- [x] Create a PR

**Comment by robinwpdeveloper** [comment]
I want to contribute to this task. :)
