### ISSUE TITLE
Page: Using Your Browser to Diagnose JavaScript Errors

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#38]
**debug/debug-javascript.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/debug/debug-javascript.md

- [x] Add into a Category 
- [x] Page creation
- [ ] Copy the original content
- [ ] Format the content 
- [ ] Create a PR

**Comment by dsmith4-godaddy** [comment]
Starting on this page

**Comment by dsmith4-godaddy** [comment]
https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/58
