### ISSUE TITLE
Page: Before You Install

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#4]
**before-install/index.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/before-install/index.md

- [x] Add into a Category 
- [x] Page creation
- [x] Copy the original content
- [x] Format the content 
- [x] Create a PR

**Comment by javiercasares** [comment]
Taken by Arnas Donauskas

**Comment by ArnasDon** [comment]
@javiercasares [PR](https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/43) ready for review&merge
