### ISSUE TITLE
Page: How to install WordPress

### ISSUE THREAD

**Issue by javiercasares** [zzap/WordPress-Advanced-administration-handbook#6]
**before-install/howto-install.md**

https://github.com/zzap/WordPress-Advanced-administration-handbook/blob/main/before-install/howto-install.md

- [x] Add into a Category 
- [x] Page creation
- [x] Copy the original content
- [x] Format the content 
- [x] Create a PR

**Comment by lucprincen** [comment]
Pull request available: https://github.com/zzap/WordPress-Advanced-administration-handbook/pull/66#issue-1372879080
